"""empty message

Revision ID: 882a908d9e22
Revises: 
Create Date: 2021-04-26 15:34:10.210393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882a908d9e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'role', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
